on:
  push:
    branches:
    - feature/*
    - master

jobs:
  build:
    name: Build RaspberryPi application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # check performance of increases in the commit depth
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.4
      with:
        versionSpec: 5.3.x
    - name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.4
      id:   gitversion

    - name: Build
      uses: docker://ghcr.io/kernelcoredump/previous-builder:latest
      with:
        # mount $GITHUB_WORKSPACE to /work or just use the mounted /github/workspace
        # workdir is automatically set to /github/workspace
        args: "/crosstools-build.sh"

    - name: Create package
      run: tar -cf previous-RPiOS.tar -C $GITHUB_WORKSPACE/build/dist .

    - name: Publish package
      uses: actions/upload-artifact@v2
      with:
        name: previous-RPiOS
        path: previous-RPiOS.tar
